var doit,winh,winw,curw;function externallinks(){var domain=window.location+'';domain=domain.replace('//','');domain=domain.substring(domain.indexOf(':')+1,domain.indexOf('/'));if(!document.getElementsByTagName)return;var anchors=document.getElementsByTagName("a");for(var i=0;i<anchors.length;i++){var URL=anchors[i].href;var curTarget=anchors[i].target;curTarget=curTarget.toLowerCase();if(curTarget==='same'){anchors[i].target="_self"}else if((URL.search(domain)===-1&&URL.search('http')!==-1&&anchors[i].rel!=='self'&&anchors[i].target!=='_self'&&anchors[i].target!=='same')||anchors[i].rel==='external'||URL.search('.pdf')!==-1){anchors[i].target="_blank"}}}
function contentmask(){var pich=0;$('article .thecontent').addClass('block');$('article .content .mask').addClass('on');$('article .alert').addClass('on');if($('.thecontent > img:first-child').length){var pich=$('.thecontent > img:first-child').height()}
if($('.thecontent > p:first-child img:first-child').length){var pich=$('.thecontent > p:first-child img:first-child').height()}
if($('.thecontent > figure:first-child:not(.alignleft) img').length||$('.thecontent > figure:first-child:not(.alignright) img').length){var pich=$('.thecontent > figure:first-child img').height()}
$('section article .thecontent.block').css('height',350+pich+'px');$('.unmask').click(function(e){e.preventDefault();contentunmask()})}
function contentunmask(){$('section article .thecontent').css('height','auto');$('article .thecontent').removeClass('block');$('article .content .mask').removeClass('on');$('article .alert').removeClass('on')}
function videodisplay(){$('article .content iframe').each(function(){var earl=$(this).attr('src');if(typeof earl!=="undefined"&&earl.indexOf('youtu')>0){$(this).wrap('<div class="res-embed-outer v-t-36"><div class="res-embed"></div></div>')}})}
function relatedposts(){var count=1;$('.rp4wp_component_image a').each(function(){var src=$(this).children('img').attr('src');$(this).css('backgroundImage','url(\''+src+'\')');$(this).html('&nbsp;');count++})}
function tablepressscroll(){$('table.tablepress').each(function(){$(this).wrap('<div class="tablescroll"></div>')})}
function trackpdfs(){$('main a').each(function(){var link=$(this).attr('href');var linkbits=link.split('/');linkbits.reverse();if(linkbits[0].includes('.pdf')===!0){$(this).click(function(){ga('send','event','PDF','Open',linkbits[0])})}})}
function recaptchanotice(){$('.gform_footer').prepend('<p style="font-size:.8rem ; padding:12px 0">Submissions protected by Google reCAPTCHA | <a href="https://policies.google.com/privacy" rel="noopener nofollow" target="_google">Privacy Policy</a> | <a href="https://policies.google.com/terms" rel="noopener nofollow" target="_google">Terms of Service</a></p>')}
$(window).load(function(){externallinks();trackpdfs();if($('article .content iframe').length)videodisplay();if($('.rp4wp-related-posts').length)relatedposts();if($('table.tablepress').length)tablepressscroll();if($('.gform_footer').length)recaptchanotice()})